[project]
name = "pubmed-rag-fastapi"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.0",
  "pydantic>=2.8.0"
]

[tool.uvicorn]
factory = false
host = "0.0.0.0"
port = 8000
reload = true